# Generated by Django 2.2.3 on 2019-07-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LPGRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.IntegerField(verbose_name='流水号')),
                ('side', models.IntegerField(verbose_name='充装数据机器号')),
                ('proportion', models.CharField(max_length=20, verbose_name='比例')),
                ('bay', models.IntegerField(verbose_name='车道')),
                ('bl_no', models.IntegerField(verbose_name='提单号')),
                ('customer_no', models.IntegerField(verbose_name='客户号')),
                ('drive_no', models.IntegerField(verbose_name='车牌号')),
                ('preset', models.IntegerField(verbose_name='预装数量')),
                ('gross', models.IntegerField(verbose_name='实际数量')),
                ('started', models.DateTimeField(verbose_name='开始时间')),
                ('stopped', models.DateTimeField(verbose_name='结束时间')),
                ('butane', models.IntegerField(verbose_name='C4 数量')),
                ('propane', models.IntegerField(verbose_name='C3 数量')),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
