# Generated by Django 2.2.3 on 2019-07-31 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpgrecord',
            name='load_database_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间'),
        ),
    ]
